apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: histershop-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hipstershop-ingress
  namespace: istio-system
spec:
  hosts:
    - "*"
  gateways:
    - histershop-gateway
  http:
  - match:
    - uri:
        prefix: /kiali
      - route:
        - destination:
            host: kiali.istio-system.svc.cluster.local
            port:
              number: 20001
    - uri:
        prefix: /grafana
      - route:
          - destination :
              host: grafana.default.svc.cluster.local
              port:
                number: 3000
    - uri:
        prefix: /hipstershop
          - route:
              - destination:
                  host: grafana.hipster-shop.local
                  port:
                    number: 3000